/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { ModelProps, GLTFResult } from "./modelTypes";

export default function Cuctos(props: ModelProps) {
  const group = useRef(null);
  const { nodes, materials } = useGLTF("/cactus.gltf") as GLTFResult;
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onPointerOver={() => {
        props.cursorIn();
      }}
      onPointerOut={() => {
        props.cursorOut();
      }}
      onClick={(current) => {
        current.stopPropagation();
        props.setSelectedUrlId(props.urls.id);
      }}
      scale={0.3}
    >
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
      />
      <mesh
        geometry={nodes.ground.geometry}
        material={materials["Material.008"]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={nodes.Cylinder007.material}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={nodes.Cylinder011.material}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={nodes.Cylinder015.material}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={nodes.Cylinder009.material}
      />
      <mesh
        geometry={nodes.cactus.geometry}
        material={materials["Material.007"]}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={nodes.Cylinder013.material}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={nodes.Cylinder017.material}
      />
      <mesh
        geometry={nodes.pot.geometry}
        material={materials["Material.006"]}
      />
    </group>
  );
}

useGLTF.preload("/cactus.gltf");
