/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { ModelProps, GLTFResult } from "./modelTypes";
import * as THREE from "three";
export default function ReactLogo(props: ModelProps) {
  const group = useRef(null);
  const { nodes } = useGLTF("/reactLogo.gltf") as GLTFResult;

  const material = new THREE.MeshStandardMaterial({
    color: new THREE.Color("#5fd3f3"),
  });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onPointerOver={() => {
        props.cursorIn();
      }}
      onPointerOut={() => {
        props.cursorOut();
      }}
      onClick={(current) => {
        current.stopPropagation();
        props.setSelectedUrlId(props.urls.id);
      }}
      scale={0.07}
    >
      <mesh
        geometry={nodes.Cube.geometry}
        material={material}
        position={[0, 1.31, 0]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <mesh
          geometry={nodes.Torus001.geometry}
          material={material}
          position={[0.34, -0.08, 0.02]}
          rotation={[-0.16, 0, -Math.PI / 2]}
          scale={[3.75, 1.47, 3]}
        />
        <mesh
          geometry={nodes.Torus003.geometry}
          material={material}
          position={[-0.04, -0.11, 0]}
          rotation={[0.89, 0, -Math.PI / 2]}
          scale={[3.75, 1.47, 3]}
        />
        <mesh
          geometry={nodes.Torus002.geometry}
          material={material}
          position={[-0.52, -0.1, 0.16]}
          rotation={[-1.18, 0, -Math.PI / 2]}
          scale={[3.75, 1.47, 3]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/reactLogo.gltf");
