/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { ModelProps, GLTFResult } from "./modelTypes";

export default function Model(props: ModelProps) {
  const group = useRef(null);
  const { nodes, materials } = useGLTF("/virus.gltf") as GLTFResult;
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onPointerOver={() => {
        props.cursorIn();
      }}
      onPointerOut={() => {
        props.cursorOut();
      }}
      onClick={(current) => {
        current.stopPropagation();
        props.setSelectedUrlId(props.urls.id);
      }}
      scale={0.1}
    >
      <mesh
        geometry={nodes.core.geometry}
        material={materials["core.001"]}
        position={[0, 1.01, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.core_3.geometry}
          material={materials["core_3.001"]}
          position={[0.3, -0.38, -0.46]}
        />
        <mesh
          geometry={nodes.core_2.geometry}
          material={materials["core_2.001"]}
          position={[0.43, -0.33, -0.36]}
        />
        <mesh
          geometry={nodes.corona.geometry}
          material={materials["corona.001"]}
          position={[0.43, -0.34, -0.36]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/virus.gltf");
